import { StyleSheet } from 'react-native';

import type { ThemeColors } from '../../constants/theme';

export function createStyles(colors: ThemeColors) {
  return StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  mapPane: {
    flex: 1,
    position: 'relative',
  },
  map: {
    width: '100%',
    height: '100%',
  },
  mapFilterStack: {
    position: 'absolute',
    left: 10,
    bottom: 10,
    zIndex: 20,
    gap: 6,
  },
  mapIconButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.borderSoft,
  },
  mapIconButtonActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentSoft,
  },
  pickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'flex-end',
  },
  pickerSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    maxHeight: '70%',
    paddingBottom: 20,
  },
  pickerScroll: {
    flexGrow: 0,
  },
  pickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  pickerTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.text,
  },
  pickerClose: {
    fontSize: 16,
    color: colors.textMuted,
    fontWeight: '600',
  },
  pickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.chip,
  },
  pickerRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    minWidth: 0,
  },
  pickerRowLabel: {
    fontSize: 13,
    color: colors.text,
    fontWeight: '500',
  },
  pickerCheck: {
    fontSize: 14,
    color: colors.accent,
    fontWeight: '700',
  },
  userMarker: {
    alignItems: 'center',
  },
  userMarkerDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.accent,
    borderWidth: 2,
    borderColor: colors.surface,
  },
  userMarkerLabel: {
    marginTop: 3,
    fontSize: 9,
    fontWeight: '600',
    color: colors.accentPressed,
    backgroundColor: colors.accentSoft,
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 4,
    overflow: 'hidden',
  },
  weatherBanner: {
    position: 'absolute',
    left: 10,
    right: 54,
    bottom: 10,
    zIndex: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.borderSoft,
  },
  weatherBannerText: {
    flex: 1,
    fontSize: 12,
    fontWeight: '600',
    color: colors.text,
  },
  poiMarkerBubble: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  poiMarkerBubbleHighlighted: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderColor: colors.accent,
    borderWidth: 2,
    backgroundColor: colors.accentSoft,
  },
  poiMarkerBubbleDimmed: {
    opacity: 0.4,
    borderColor: colors.border,
  },
  poiMarkerBubbleAdmin: {
    borderColor: colors.danger,
    borderStyle: 'dashed',
  },
  adminBadge: {
    position: 'absolute',
    top: 48,
    alignSelf: 'center',
    backgroundColor: 'rgba(220, 38, 38, 0.88)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    zIndex: 5,
  },
  adminBadgeText: {
    color: colors.textOnAccent,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  poiMarkerEmoji: {
    fontSize: 14,
  },
  poiMarkerEmojiSelected: {
    fontSize: 16,
  },
  detailPanel: {
    flex: 1,
  },
  detailPanelContent: {
    paddingHorizontal: 12,
    paddingBottom: 16,
  },
  detailTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  backButton: {
    paddingVertical: 2,
    paddingRight: 6,
  },
  backButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.accent,
  },
  categoryBadge: {
    backgroundColor: colors.accentSoft,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  categoryBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.accentPressed,
    flexShrink: 1,
  },
  detailNameRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 6,
  },
  detailName: {
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
    flexShrink: 1,
    minWidth: 0,
  },
  sponsorChip: {
    marginTop: 2,
    backgroundColor: colors.warningSoft,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  sponsorChipText: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.warning,
  },
  hoursOpen: {
    color: colors.success,
    fontWeight: '700',
  },
  hoursClosed: {
    color: '#B42318',
    fontWeight: '700',
  },
  detailMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 8,
  },
  detailMeta: {
    fontSize: 12,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  detailDescription: {
    fontSize: 12,
    lineHeight: 17,
    color: colors.textSecondary,
    marginBottom: 12,
  },
  detailPrice: {
    color: colors.accent,
    fontWeight: '700',
  },
  panelAmenities: {
    marginBottom: 12,
    padding: 10,
    borderRadius: 10,
    backgroundColor: colors.chip,
    gap: 4,
  },
  panelAmenitiesToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  panelAmenitiesTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.text,
  },
  panelAmenitiesHint: {
    fontSize: 12,
    color: colors.textMuted,
    fontWeight: '700',
  },
  panelAmenityItem: {
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 18,
  },
  detailActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 12,
  },
  actionButton: {
    backgroundColor: colors.chip,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  deleteActionButton: {
    backgroundColor: colors.dangerSoft,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.danger,
  },
  deleteActionButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.danger,
  },
  actionButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.text,
  },
  shareHeaderButton: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  profileCorner: {
    position: 'absolute',
    top: 10,
    right: 10,
    zIndex: 12,
  },
  locateButton: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.borderSoft,
    zIndex: 10,
  },
  listPane: {
    flex: 1,
    backgroundColor: colors.surface,
    paddingTop: 4,
  },
  listHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    marginBottom: 4,
    gap: 8,
  },
  listHeaderTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  listTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
  },
  listWeather: {
    marginTop: 2,
    fontSize: 11,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  shareHeaderHit: {
    flexShrink: 0,
  },
  listContent: {
    paddingHorizontal: 10,
    paddingBottom: 12,
  },
  card: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bg,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 6,
    marginBottom: 4,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.borderSoft,
  },
  cardHighlighted: {
    backgroundColor: colors.accentSoft,
    borderColor: colors.accent,
    borderWidth: 1,
  },
  cardDimmed: {
    opacity: 0.45,
  },
  cardEmojiWrap: {
    width: 48,
    height: 48,
    borderRadius: 10,
    backgroundColor: colors.chip,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardThumb: {
    width: 48,
    height: 48,
    borderRadius: 10,
    backgroundColor: colors.chip,
  },
  cardEmoji: {
    fontSize: 15,
  },
  panelGalleryBlock: {
    marginBottom: 10,
    gap: 8,
  },
  panelHeroImage: {
    width: '100%',
    height: 150,
    borderRadius: 12,
    backgroundColor: colors.chip,
  },
  panelThumbRow: {
    gap: 6,
    paddingRight: 4,
  },
  panelThumbWrap: {
    borderRadius: 8,
    borderWidth: 2,
    borderColor: 'transparent',
    overflow: 'hidden',
  },
  panelThumbWrapActive: {
    borderColor: colors.accent,
  },
  panelThumb: {
    width: 64,
    height: 48,
    borderRadius: 6,
    backgroundColor: colors.chip,
  },
  panelGalleryPlaceholder: {
    height: 100,
    borderRadius: 12,
    marginBottom: 10,
    backgroundColor: colors.chip,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardBody: {
    flex: 1,
    minWidth: 0,
    marginLeft: 8,
    justifyContent: 'center',
  },
  cardTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  cardName: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
  },
  cardMetaRight: {
    alignItems: 'flex-end',
    flexShrink: 0,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  ratingStar: {
    fontSize: 10,
    color: colors.warning,
  },
  ratingText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.chipText,
  },
  distanceText: {
    marginTop: 1,
    fontSize: 10,
    color: colors.textMuted,
    fontWeight: '500',
  },
  cardPrice: {
    marginTop: 2,
    fontSize: 10,
    fontWeight: '700',
    color: colors.accent,
  },
  cardCategory: {
    marginTop: 1,
    fontSize: 11,
    color: colors.textMuted,
  },
  loader: {
    marginTop: 20,
  },
  errorText: {
    marginHorizontal: 12,
    color: colors.dangerText,
    fontSize: 12,
  },
  emptyWrap: {
    alignItems: 'center',
    marginTop: 20,
    paddingHorizontal: 20,
  },
  emptyTitle: {
    color: colors.chipText,
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  emptySubtitle: {
    marginTop: 4,
    color: colors.textMuted,
    fontSize: 12,
    textAlign: 'center',
  },
});
}
