import { StyleSheet } from 'react-native';

import type { ThemeColors } from '../constants/theme';

export function createStyles(colors: ThemeColors) {
  return StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: colors.overlay,
  },
  sheet: {
    maxHeight: '92%',
    backgroundColor: colors.bg,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    paddingTop: 8,
    overflow: 'hidden',
  },
  handle: {
    alignSelf: 'center',
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.border,
    marginBottom: 4,
  },
  toastHost: {
    position: 'absolute',
    left: 16,
    right: 16,
    zIndex: 30,
    alignItems: 'center',
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.chip,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetHeader: {
    position: 'absolute',
    top: 18,
    right: 14,
    zIndex: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 8,
    paddingBottom: 80,
    flexGrow: 1,
  },
  badge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginBottom: 12,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: '700',
  },
  title: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.text,
    marginBottom: 12,
    paddingRight: 88,
    letterSpacing: -0.3,
  },
  descriptionCard: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 14,
    marginBottom: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.borderSoft,
  },
  descriptionText: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.textSecondary,
  },
  infoCard: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    paddingVertical: 4,
    paddingHorizontal: 4,
    marginBottom: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.borderSoft,
  },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surfaceMuted,
  },
  infoFact: {
    width: '47%',
    flexGrow: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 6,
    minWidth: '42%',
  },
  infoIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: colors.accentSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoFactBody: {
    flex: 1,
    minWidth: 0,
  },
  infoFactLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textMuted,
    marginBottom: 2,
  },
  infoFactValue: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
    flexShrink: 1,
    minWidth: 0,
  },
  creatorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 14,
  },
  creatorNameLg: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.text,
    maxWidth: 220,
  },
  avatarAccent: {
    backgroundColor: '#F59E0B',
  },
  avatarInitialAccent: {
    fontSize: 18,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  headerFavWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: colors.warningSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickActionsRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  quickActionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 10,
  },
  quickActionText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 13,
  },
  metaLinksRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'nowrap',
    gap: 8,
    marginBottom: 10,
  },
  metaActionBtn: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 8,
    minHeight: 40,
    backgroundColor: colors.surfaceMuted,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.borderSoft,
  },
  metaActionBtnSolo: {
    flex: 1,
    alignSelf: 'stretch',
  },
  metaBlock: {
    marginBottom: 4,
  },
  routeListCard: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    marginBottom: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.borderSoft,
    overflow: 'hidden',
  },
  poiIndex: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.accentSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  poiIndexText: {
    fontSize: 11,
    fontWeight: '800',
    color: colors.accent,
  },
  poiItemBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.borderSoft,
  },
  poiItemPad: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginLeft: 0,
  },
  creatorActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 16,
  },
  creatorLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexShrink: 1,
    minWidth: 0,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
  },
  avatarPlaceholder: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarInitial: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.chipText,
  },
  creatorMeta: {
    flexShrink: 1,
    minWidth: 0,
    gap: 4,
  },
  creatorNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  creatorName: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
    maxWidth: 120,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  ratingLoading: {
    fontSize: 11,
    color: colors.textMuted,
  },
  sideActions: {
    flexShrink: 0,
    alignItems: 'stretch',
    justifyContent: 'center',
    gap: 6,
    marginLeft: 'auto',
  },
  sideActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 10,
    minWidth: 0,
    maxWidth: '100%',
    alignSelf: 'stretch',
  },
  sideActionText: {
    color: colors.textOnAccent,
    fontWeight: '700',
    fontSize: 12,
    flexShrink: 1,
  },
  whatsappButton: {
    backgroundColor: colors.whatsapp,
  },
  whatsappButtonDisabled: {
    backgroundColor: colors.textMuted,
    opacity: 0.9,
  },
  splitBillButton: {
    backgroundColor: '#3B82F6',
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 8,
  },
  subscribersWrap: {
    marginTop: 0,
    marginBottom: 8,
    gap: 8,
  },
  subscribersPill: {
    flex: 1,
    minWidth: 0,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 8,
    minHeight: 40,
    backgroundColor: colors.surfaceMuted,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.borderSoft,
  },
  subscribersPillText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.brand,
    flexShrink: 1,
  },
  subscribersPanel: {
    borderRadius: 14,
    backgroundColor: colors.surfaceMuted,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.borderSoft,
    overflow: 'hidden',
  },
  subscribersEmpty: {
    fontSize: 13,
    color: colors.textMuted,
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  subscriberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  subscriberRowBorder: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.borderSoft,
  },
  subscriberAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  subscriberAvatarPlaceholder: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.accentSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  subscriberAvatarInitial: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.accentPressed,
  },
  subscriberName: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
  },
  routeToggleText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.brand,
    flexShrink: 1,
  },
  poiItem: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 0,
  },
  poiItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 11,
    paddingHorizontal: 12,
  },
  muted: {
    fontSize: 13,
    color: colors.textMuted,
    marginBottom: 8,
  },
  inlineLoader: {
    alignSelf: 'flex-start',
    marginBottom: 8,
  },
  actions: {
    marginTop: 16,
    marginBottom: 20,
    gap: 10,
  },
  joinButton: {
    backgroundColor: colors.brand,
    borderRadius: 16,
    paddingVertical: 15,
    alignItems: 'center',
  },
  joinButtonText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 15,
  },
  disabledButton: {
    backgroundColor: colors.border,
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
  },
  disabledButtonText: {
    color: colors.textMuted,
    fontWeight: '700',
    fontSize: 15,
  },
  joinForm: {
    gap: 8,
  },
  messageInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    minHeight: 80,
    paddingHorizontal: 12,
    paddingVertical: 10,
    textAlignVertical: 'top',
    color: colors.text,
  },
  primaryButton: {
    backgroundColor: colors.accent,
    borderRadius: 16,
    paddingVertical: 13,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: colors.textOnAccent,
    fontWeight: '700',
    fontSize: 14,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  ownerButton: {
    borderWidth: 1,
    borderColor: colors.accent,
    borderRadius: 16,
    paddingVertical: 13,
    alignItems: 'center',
  },
  ownerButtonText: {
    color: colors.accent,
    fontWeight: '700',
    fontSize: 14,
  },
  deleteTextButton: {
    alignItems: 'center',
    paddingVertical: 8,
  },
  deleteText: {
    color: colors.danger,
    fontWeight: '700',
    fontSize: 14,
  },
  reportButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: '#FECACA',
    backgroundColor: colors.dangerSoft,
    borderRadius: 16,
    paddingVertical: 12,
  },
  reportButtonText: {
    color: colors.dangerText,
    fontWeight: '700',
    fontSize: 14,
  },
  reportForm: {
    gap: 8,
    borderWidth: 1,
    borderColor: '#FECACA',
    backgroundColor: colors.dangerSoft,
    borderRadius: 12,
    padding: 12,
  },
  reportTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#991B1B',
  },
  reasonChip: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  reasonChipSelected: {
    borderColor: colors.dangerText,
    backgroundColor: colors.dangerSoft,
  },
  reasonChipText: {
    color: colors.chipText,
    fontSize: 13,
    fontWeight: '600',
  },
  reasonChipTextSelected: {
    color: colors.dangerText,
  },
  reportSubmit: {
    backgroundColor: colors.dangerText,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
  },
  cancelReport: {
    textAlign: 'center',
    color: colors.textSecondary,
    fontWeight: '600',
    marginTop: 4,
  },
  adminActions: {
    gap: 8,
    marginTop: 4,
  },
  participantsBlock: {
    marginTop: 4,
    gap: 10,
  },
  participantRow: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 12,
    flexDirection: 'row',
    gap: 10,
    alignItems: 'flex-start',
  },
  participantAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  participantAvatarPlaceholder: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  participantAvatarInitial: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.chipText,
  },
  participantInfo: {
    flex: 1,
  },
  participantName: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
  },
  participantMessage: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 4,
  },
  statusBadge: {
    alignSelf: 'flex-start',
    marginTop: 8,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: '700',
  },
  participantActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  approveButton: {
    borderRadius: 16,
    backgroundColor: colors.successSoft,
    paddingHorizontal: 12,
    paddingVertical: 8,
    minWidth: 96,
    alignItems: 'center',
  },
  approveButtonText: {
    color: colors.success,
    fontWeight: '700',
    fontSize: 13,
  },
  rejectButton: {
    borderRadius: 16,
    backgroundColor: colors.dangerSoft,
    paddingHorizontal: 12,
    paddingVertical: 8,
    minWidth: 96,
    alignItems: 'center',
  },
  rejectButtonText: {
    color: colors.dangerText,
    fontWeight: '700',
    fontSize: 13,
  },
  rejectReasonBlock: {
    marginTop: 10,
    gap: 8,
  },
  rejectReasonLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textMuted,
  },
  templateScroll: {
    flexGrow: 0,
  },
  templateChip: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 6,
  },
  templateChipActive: {
    backgroundColor: colors.dangerSoft,
    borderColor: colors.dangerText,
  },
  templateChipText: {
    fontSize: 12,
    color: colors.textMuted,
  },
  templateChipTextActive: {
    color: colors.dangerText,
    fontWeight: '600',
  },
  rejectInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13,
    color: colors.text,
    backgroundColor: colors.surface,
  },
  cancelRejectButton: {
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  cancelRejectText: {
    color: colors.textMuted,
    fontSize: 13,
  },
  errorText: {
    marginTop: 12,
    color: colors.dangerText,
    fontSize: 13,
  },
  successText: {
    marginTop: 12,
    color: colors.success,
    fontSize: 13,
    fontWeight: '600',
  },
});
}
